apiVersion: v1
kind: Service
metadata:
  name: msvc-process
spec:
  selector:
    app: msvc-process
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 17091
      nodePort: 30084
  type: NodePort