apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-int
spec:
  selector:
    matchLabels:
      app: msvc-int
  replicas: 1
  template:
    metadata:
      labels:
        app: msvc-int
    spec:
      containers:
        - name: msvc-int
          image: docker.io/manuericsson/msvcint
          imagePullPolicy: Always
          ports:
            - containerPort: 17092