#logging.level.org.springframework.cloud.kubernetes: DEBUG
spring.application.name: msvc-process
server:
  port: 17091

management:
  endpoints:
    web:
      exposure:
        include: info,refresh,keepalive,health
#intlyr:
#  url: http://localhost:17092
